### ISSUE TITLE
Questions about CLIP-PEGP results in journal version

### ISSUE THREAD

**Issue by PixelChen24** [JingyangQiao/prompt-gradient-projection#2]
Hi, thank you for your fantastic work!

I'm interested in your recent journal paper `Gradient Projection For Continual Parameter-Efficient Tuning`. In this paper, you demonstrate the results of incorporating PEGP into CLIP fine-tuning. In Tab3, you compare the CLIP-PEGP with your previous ICLR2024 work CLIP-PGP(The code in this repository I think) and report a 82.36 $AA$ which is much higher than 79.47 of CLIP-PGP. These two rows are both based on prompt-tuning, so I'm confused what's the difference between these two methods?

Moreover, in the ICLR2024 work, CLIP-PGP reports 79.47 $AA$ and 4.23 $FM$ with prompt length 5(as written in Appendidx G). These two metrics are exactly the same as that in your recent journal version Tab3, however the prompt length is 10(as written in 4.3.2). I wonder does prompt length not matter? How do two different prompt length lead to exactly the sametwo  results?

Look forward for your response, thank you very much.

**Comment by JingyangQiao** [comment]
Hi, pixel, we are very glad to see that you have interests in our work. Thank you for your concerns!

Firstly, the differences between the ICLR2024 and our journal extension version are clarified in the **4.2 Implementation Details**: ”_improve our gradient projection method by following [31], which linearly merges two models with/without gradient projection method [38]._” In summary, we utilize a more advanced and efficient gradient projection method. 

Secondly, the prompt length does matter, and the prompt length (10 as written in 4.3.2) only refers to the setting for the journal, not for the conference. Please notice here, that we do not distinguish the length of prompt in Tab 3(as in the journal paper). If we really distinguish the length, we will mark it as “prompt-10”, just like the way in Tab 1. 

Hope the above can address your concerns.

**Comment by PixelChen24** [comment]
I see, thank you for your explanation.

By the way, do you plan to release more code about your journal work, such as clip adaptor PEGP, clip lora PEGP? I'm really interested in your work and hope for your code.

**Comment by JingyangQiao** [comment]
Yes, we have the plan, we can share the prompt version of CLIP-PEGP this week, and the linear adapter version soon. However, it is a pity that we do not have LoRA version.

**Comment by PixelChen24** [comment]
It's a real pity if you don't release the LoRA-PEGP! In the analysis of your paper, LoRA and Adaptor share the same pattern, I wonderwhy don't you implement the LoRA-PEGP code after releasing adaptor?

**Comment by JingyangQiao** [comment]
We have published the CLIP-PEGP code at https://github.com/JingyangQiao/PEGP. You can find the CLIP-PEGP-Prompt currently. We will publish the CLIP-PEGP-Adapter and VIT-PEGP series soon. Because we don't mention CLIP-PEGP-LoRA in our paper and we are busy with other papers. We cancel the implementation of CLIP-PEGP-LoRA. Furthermore, the similar mathematical pattern of Adapter and LoRA doesn't refer to the similar code pattern.

**Comment by PixelChen24** [comment]
> We have published the CLIP-PEGP code at https://github.com/JingyangQiao/PEGP. You can find the CLIP-PEGP-Prompt currently. We will publish the CLIP-PEGP-Adapter and VIT-PEGP series soon. Because we don't mention CLIP-PEGP-LoRA in our paper and we are busy with other papers. We cancel the implementation of CLIP-PEGP-LoRA. Furthermore, the similar mathematical pattern of Adapter and LoRA doesn't refer to the similar code pattern.

OK, thank you for your patient explanations.
